cn:
  location: "地点："
  you-can-also: "您也可以："
  donate: "捐赠"
  time: "每周五晚，周六不定期加场"
  performance: "时间："
  buy-tickets: "购票"
  except-holidays: "，公共假期前除外"
en:
  except-holidays: ", except public holidays"
  buy-tickets: "Buy Tickets"
  donate: "Donate"
  time: "Every Friday night, with occasional additional shows on Saturdays"
  location: "Location: "
  performance: "Time: "
  you-can-also: "You can also: "
